### ISSUE TITLE
List of repos should auto update 

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/wicg.io#3]
The list on the front page should automatically update. We can use the GH API for that: 
https://api.github.com/orgs/wicg/repos

**Comment by marcoscaceres** [comment]
So, we have the problem that GH will only let us do 60 requests / hour unless we get a token... but putting the token in the clear defeats the purpose. 

Not sure how to do this without some pain... I guess we could just move the site to Dreamhost (or a Node-based host) and serve it from there. 

@yoavweiss, who is the domain currently registered with? Do you have hosting?

**Comment by yoavweiss** [comment]
I'm hosting it on digital ocean, so can store the token there, but unless we want to send the token as part of the JS, that means we have to create some server side logic that queries GH and stores it there.

I have to say that it'd also make for faster rendering, so all in all I'm for it. Just need to find the time to make it happen.

**Comment by marcoscaceres** [comment]
@yoavweiss, I'm happy to code it up. It will be super simple. Does digital ocean support Node or just P vomit H vomit P?

**Comment by marcoscaceres** [comment]
... vomit. :)

**Comment by marcoscaceres** [comment]
yay! I has node!!! https://www.digitalocean.com/features/one-click-apps/node-js/

**Comment by marcoscaceres** [comment]
it*

**Comment by yoavweiss** [comment]
Yeah, it's my own virtual server so node is just an apt-get away

**Comment by marcoscaceres** [comment]
Ok, so basically, we could set up a little express server and go from there 💃 I'll do a little reading up.

**Comment by darobin** [comment]
You know, at 60 requests per hour you could have a cron job dump the JSON in your Web root every 2 minutes — that's basically a `curl` away.

**Comment by marcoscaceres** [comment]
> On 9 Jun 2016, at 11:38 PM, Robin Berjon notifications@github.com wrote:
> 
> You know, at 60 requests per hour you could have a cron job dump the JSON in your Web root every 2 minutes — that's basically a curl away.

True, we could do that... But you left us and it still hurts too much 💔

**Comment by marcoscaceres** [comment]
But seriously, we could see if there is org level hooks on GH.

**Comment by darobin** [comment]
Awww poor thing. 😽 

Yes, there are org-level hooks — same API, same everything. Ash-Nazg uses them for the w3c org.

**Comment by marcoscaceres** [comment]
Ok, so that makes it super trivial. We just need to set up an end-point somewhere that fetches  https://api.github.com/orgs/wicg/repos and writes it to a file (which we can then fetch). 

@yoavweiss, if you can provide me with the hosting for the end-point, I'm happy to slap it together.

**Comment by yoavweiss** [comment]
@marcoscaceres ping me with your public ssh key and I'll add you to the server

**Comment by yoavweiss** [comment]
:wave:

**Comment by marcoscaceres** [comment]
Found a solution! https://github.com/WICG/admin/blob/gh-pages/biblio.json
